services:
  api:
    build: ./SpringBoot
    ports:
      - "8080:8080"
    networks:
      - redWeb
    depends_on:
      - db
    restart: always


  db:
    build: ./Postgres
    networks:
      - redWeb
    restart: always


  next:
    build: ./Next
    ports:
      - "3000:3000"
    networks:
      - redWeb
    depends_on:
      - api
    restart: always


networks:
  redWeb:
    driver: bridge
