spring.application.name=recipesorg-api

spring.datasource.url=jdbc:postgresql://localhost:5432/recipesorg
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

# JWT settings
jwt.secret=C0NtR07S3cR5Ts@4%6hSf
jwt.expiration-ms=3600000